### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by mokane99** [dhasenan/subtex#5]
The instructions aren't clear. 
Where is the Subtex syntax? Which commands can be used?
What can you use then to generate the .epub file?

**Comment by dhasenan** [comment]
This is covered in the README, and in the documents it references.

https://github.com/dhasenan/subtex#invocation describes how to run the program. It requires you to be comfortable working from the command line.

https://github.com/dhasenan/subtex#language describes the language, referencing [the examples folder](https://github.com/dhasenan/subtex/tree/master/examples) and [the language reference](https://github.com/dhasenan/subtex/blob/master/language.md).
